[badges]
[badges.appveyor]
repository = "Manishearth/rust-clippy"

[badges.travis-ci]
repository = "Manishearth/rust-clippy"

[[bin]]
name = "cargo-clippy"
test = false

[dependencies]
cargo_metadata = "0.1.1"

[dependencies.clippy_lints]
version = "0.0.112"

[dev-dependencies]
compiletest_rs = "0.2.5"
lazy_static = "0.1.15"
regex = "0.2"
serde = "0.9.1"
serde_derive = "0.9.1"

[dev-dependencies.clippy-mini-macro-test]
version = "0.1"

[features]
debugging = []

[lib]
name = "clippy"
plugin = true
test = false

[package]
authors = ["Manish Goregaokar <manishsmail@gmail.com>", "Andre Bogus <bogusandre@gmail.com>", "Georg Brandl <georg@python.org>", "Martin Carton <cartonmartin@gmail.com>", "Oliver Schneider <clippy-iethah7aipeen8neex1a@oli-obk.de>"]
categories = ["development-tools", "development-tools::cargo-plugins"]
description = "A bunch of helpful lints to avoid common pitfalls in Rust"
keywords = ["clippy", "lint", "plugin"]
license = "MPL-2.0"
name = "clippy"
readme = "README.md"
repository = "https://github.com/Manishearth/rust-clippy"
version = "0.0.112"
