[dependencies]
[dependencies.frunk_core]
version = "0.0.1"

[dependencies.frunk_derives]
version = "0.0.1"

[package]
authors = ["Lloyd <lloydmeta@gmail.com>"]
description = "Frunk provides developers with a number of functional programming tools like HList, Generic, Validated, Monoid, Semigroup and friends."
homepage = "https://github.com/lloydmeta/frunk"
keywords = ["HList", "Generic", "Validated", "Semigroup", "Monoid"]
license = "MIT"
name = "frunk"
version = "0.1.9"
