[dependencies]
[dependencies.gazetta-cli]
version = "0.2"

[dependencies.gazetta-core]
version = "0.2"

[dependencies.gazetta-model-ext]
version = "0.2"

[dependencies.gazetta-render-ext]
version = "0.2"

[package]
authors = ["Steven Allen <steven@stebalien.com>"]
description = "A static site generator framework.\n\nIf you want to use or extend gazetta, see the gazetta-bin crate.\n"
documentation = "https://stebalien.github.io/gazetta/gazetta/"
homepage = "http://stebalien.com/projects/gazetta"
keywords = ["staticsite", "website", "blog"]
license = "GPL-3.0"
name = "gazetta"
repository = "https://github.com/Stebalien/gazetta"
version = "0.2.0"
