[dev-dependencies]
[dev-dependencies.gc_derive]
version = "0.3.0"

[features]
nightly = []

[package]
authors = ["Manish Goregaokar <manishsmail@gmail.com>", "Michael Layzell <michael@thelayzells.com>"]
description = "Tracing garbage collector plugin for Rust. Not ready for use yet, please see README"
keywords = ["garbage", "plugin", "memory"]
license = "MPL-2.0"
name = "gc"
readme = "../README.md"
repository = "https://github.com/Manishearth/rust-gc"
version = "0.3.0"
