[[bin]]
name = "blogger3"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.9"
serde_derive = "^ 0.9"
serde_json = "^ 0.9"
strsim = "^0.5"
yup-hyper-mock = "^2.0"
yup-oauth2 = "^ 1.0"

[dependencies.google-blogger3]
version = "1.0.4+20150422"

[features]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with blogger (protocol v3)"
documentation = "http://byron.github.io/google-apis-rs/google_blogger3_cli"
homepage = "https://developers.google.com/blogger/docs/3.0/getting_started"
keywords = ["blogger", "google", "cli"]
license = "MIT"
name = "google-blogger3-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/blogger3-cli"
version = "1.0.4+20150422"
