[[bin]]
name = "sqladmin1-beta4"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.9"
serde_derive = "^ 0.9"
serde_json = "^ 0.9"
strsim = "^0.5"
yup-hyper-mock = "^2.0"
yup-oauth2 = "^ 1.0"

[dependencies.google-sqladmin1_beta4]
version = "1.0.4+20161213"

[features]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with SQL Admin (protocol v1beta4)"
documentation = "http://byron.github.io/google-apis-rs/google_sqladmin1_beta4_cli"
homepage = "https://cloud.google.com/sql/docs/reference/latest"
keywords = ["sqladmin", "google", "cli"]
license = "MIT"
name = "google-sqladmin1_beta4-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/sqladmin1_beta4-cli"
version = "1.0.4+20161213"
