[features]
default = ["use_std"]
use_std = []

[package]
authors = ["The Rust Project Developers"]
description = "A library for types and bindings to native C functions often found in libc or\nother common platform libraries.\n"
documentation = "http://doc.rust-lang.org/libc"
homepage = "https://github.com/rust-lang/libc"
license = "MIT/Apache-2.0"
name = "libc"
readme = "README.md"
repository = "https://github.com/rust-lang/libc"
version = "0.2.20"
