[dependencies]
range = "0.3.1"

[dependencies.piston_meta]
version = "0.29.0"

[package]
authors = ["bvssvni <bvssvni@gmail.com>"]
description = "A search API for piston_meta"
homepage = "https://github.com/pistondevelopers/meta"
keywords = ["meta", "language", "search", "piston"]
license = "MIT"
name = "piston_meta_search"
readme = "README.md"
repository = "https://github.com/pistondevelopers/meta.git"
version = "0.16.0"
