[dependencies]
bitflags = "0.7"
lazy_static = "0.2"
libc = "0.2"
rand = "0.3"

[dependencies.c_vec]
optional = true
version = "1.0.*"

[dependencies.num]
default-features = false
version = "0.1.25"

[dependencies.sdl2-sys]
version = "0.27"

[features]
default = []
gfx = ["c_vec"]
image = []
mixer = []
ttf = []
use-pkgconfig = ["sdl2-sys/use-pkgconfig"]
use_mac_framework = ["sdl2-sys/use_mac_framework"]

[lib]
name = "sdl2"
path = "src/sdl2/lib.rs"

[package]
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]
description = "SDL2 bindings for Rust"
documentation = "http://angrylawyer.github.io/rust-sdl2/sdl2/"
keywords = ["SDL", "windowing", "graphics"]
license = "MIT"
name = "sdl2"
repository = "https://github.com/AngryLawyer/rust-sdl2"
version = "0.28.0"

[[test]]
harness = false
name = "events"
