[badges]
[badges.travis-ci]
repository = "serde-rs/serde"

[dependencies]
[dependencies.serde]
version = "0.9"

[package]
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
description = "Token De/Serializer for testing De/Serialize implementations"
documentation = "https://docs.serde.rs/serde_test/"
homepage = "https://serde.rs"
include = ["Cargo.toml", "src/**/*.rs"]
keywords = ["serde", "serialization"]
license = "MIT/Apache-2.0"
name = "serde_test"
readme = "../README.md"
repository = "https://github.com/serde-rs/serde"
version = "0.9.7"
