[dependencies]
libc = "0.1"

[dependencies.allegro]
version = "=0.0.30"

[dependencies.allegro_image-sys]
version = "=0.0.30"

[dependencies.allegro_util]
version = "=0.0.30"

[features]
link_debug = ["allegro_image-sys/link_debug"]
link_none = ["allegro_image-sys/link_none"]
link_static = ["allegro_image-sys/link_static"]

[lib]
name = "allegro_image"
path = "src/lib.rs"

[package]
authors = ["SiegeLord <slabode@aim.com>"]
description = "Allegro 5 image addon Rust wrapper"
documentation = "http://siegelord.github.io/RustAllegro/doc/allegro_image/index.html"
keywords = ["image", "graphics"]
license = "Zlib"
name = "allegro_image"
repository = "https://github.com/SiegeLord/RustAllegro"
version = "0.0.30"
