[dependencies]
libc = "0.1"

[dependencies.allegro-sys]
version = "=0.0.30"

[dependencies.allegro_util]
version = "=0.0.30"

[features]
link_debug = []
link_none = []
link_static = []

[lib]
name = "allegro_color_sys"
path = "src/lib.rs"

[package]
authors = ["SiegeLord <slabode@aim.com>"]
build = "build.rs"
description = "Allegro 5 color addon Rust binding"
documentation = "http://siegelord.github.io/RustAllegro/doc/allegro_color-sys/index.html"
keywords = ["color"]
license = "Zlib"
links = "allegro_color"
name = "allegro_color-sys"
repository = "https://github.com/SiegeLord/RustAllegro"
version = "0.0.30"
