[[bin]]
name = "drive3"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.9"
serde_derive = "^ 0.9"
serde_json = "^ 0.9"
strsim = "^0.5"
yup-hyper-mock = "^2.0"
yup-oauth2 = "^ 1.0"

[dependencies.google-drive3]
version = "1.0.4+20161212"

[features]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with drive (protocol v3)"
documentation = "http://byron.github.io/google-apis-rs/google_drive3_cli"
homepage = "https://developers.google.com/drive/"
keywords = ["drive", "google", "cli"]
license = "MIT"
name = "google-drive3-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/drive3-cli"
version = "1.0.4+20161212"
