[dependencies]
nalgebra = "0.8.*"
num = "0.1.*"
rustc-serialize = "0.3.*"

[dependencies.ncollide_entities]
version = "0.5.*"

[dependencies.ncollide_math]
version = "0.3.*"

[dependencies.ncollide_utils]
version = "0.3.*"

[lib]
name = "ncollide_queries"
path = "lib.rs"

[package]
authors = ["SÃ©bastien Crozet <developer@crozet.re>"]
description = "2 and 3-dimensional collision detection library in Rust: module for geometric queries like distances computation, ray casting and contact determination."
documentation = "http://ncollide.org/doc/ncollide_queries"
homepage = "http://ncollide.org"
keywords = ["collision", "geometry", "distance", "ray", "convex"]
license = "BSD-3-Clause"
name = "ncollide_queries"
repository = "https://github.com/sebcrozet/ncollide"
version = "0.4.0"
