[dependencies]
[dependencies.quickcheck]
version = "0.3"

[lib]
name = "quickcheck_macros"
path = "src/lib.rs"
plugin = true

[package]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A macro attribute for quickcheck."
documentation = "http://burntsushi.net/rustdoc/quickcheck/"
homepage = "https://github.com/BurntSushi/quickcheck"
keywords = ["testing", "quickcheck", "property", "shrinking", "fuzz"]
license = "Unlicense/MIT"
name = "quickcheck_macros"
readme = "../README.md"
repository = "https://github.com/BurntSushi/quickcheck"
version = "0.2.29"

[[test]]
name = "attribute"
path = "examples/attribute.rs"
