[build-dependencies]
ansi_term = "^0.9"
version_check = "^0.1"

[dependencies]
log = "^0.3"

[dependencies.rocket]
version = "0.2.0"

[dev-dependencies]
compiletest_rs = "^0.2"

[lib]
plugin = true

[package]
authors = ["Sergio Benitez <sb@sergio.bz>"]
build = "build.rs"
description = "Code generation for the Rocket web framework."
documentation = "https://api.rocket.rs/rocket_codegen/"
homepage = "https://rocket.rs"
keywords = ["rocket", "web", "framework", "code", "generation"]
license = "MIT/Apache-2.0"
name = "rocket_codegen"
readme = "../README.md"
repository = "https://github.com/SergioBenitez/Rocket"
version = "0.2.0"
