[badges]
[badges.appveyor]
repository = "antiagainst/rspirv"

[badges.travis-ci]
repository = "google/rspirv"

[dependencies]
num = "0.1"
num-derive = "0.1"

[dependencies.spirv_headers]
version = "1.1"

[dev-dependencies]
assert_matches = "1.0"

[lib]
path = "lib.rs"

[package]
authors = ["Lei Zhang <antiagainst@gmail.com>"]
description = "Rust library APIs for SPIR-V module manipulation"
documentation = "https://docs.rs/rspirv"
keywords = ["spirv", "vulkan", "opengl", "opencl"]
license = "Apache-2.0"
name = "rspirv"
readme = "README.md"
repository = "https://github.com/google/rspirv"
version = "0.3.3"
