[build-dependencies]
[build-dependencies.schemafy_snapshot]
version = "0.2.0"

[dependencies]
Inflector = "0.6.0"
quote = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[package]
authors = ["Markus Westerlind <marwes91@gmail.com>"]
build = "build.rs"
description = "Generates serializeable Rust types from a json schema"
documentation = "https://docs.rs/schemafy"
license = "MIT"
name = "schemafy"
repository = "https://github.com/Marwes/schemafy"
version = "0.2.1"
