[badges]
[badges.travis-ci]
repository = "serde-rs/serde"

[dependencies]
quote = "0.3.8"

[dependencies.serde_codegen_internals]
default-features = false
version = "=0.13.0"

[dependencies.syn]
features = ["aster", "visit"]
version = "0.11"

[features]
unstable = []

[lib]
name = "serde_derive"
proc-macro = true

[package]
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
description = "Macros 1.1 implementation of #[derive(Serialize, Deserialize)]"
documentation = "https://serde.rs/codegen.html"
homepage = "https://serde.rs"
include = ["Cargo.toml", "src/**/*.rs"]
keywords = ["serde", "serialization", "no_std"]
license = "MIT/Apache-2.0"
name = "serde_derive"
repository = "https://github.com/serde-rs/serde"
version = "0.9.7"
