[dependencies]
[dependencies.glsl-to-spirv]
version = "0.1.0"

[package]
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Shaders "
documentation = "http://tomaka.github.io/vulkano/vulkano/index.html"
license = "MIT/Apache-2.0"
name = "vulkano-shaders"
repository = "https://github.com/tomaka/vulkano"
version = "0.2.2"
