[dependencies]
libc = "0.1"

[dependencies.allegro_util]
version = "=0.0.29"

[features]
link_debug = []
link_none = []
link_static = []

[lib]
name = "allegro_acodec_sys"
path = "src/lib.rs"

[package]
authors = ["SiegeLord <slabode@aim.com>"]
build = "build.rs"
description = "Allegro 5 acodec addon Rust binding"
documentation = "http://siegelord.github.io/RustAllegro/doc/allegro_acodec-sys/index.html"
keywords = ["audio"]
license = "Zlib"
links = "allegro_acodec"
name = "allegro_acodec-sys"
repository = "https://github.com/SiegeLord/RustAllegro"
version = "0.0.29"
