[[bin]]
doc = false
name = "cargo"
test = false

[dependencies]
advapi32-sys = "0.2"
crossbeam = "0.2"
curl = "0.4"
docopt = "0.6"
env_logger = "0.3"
filetime = "0.1"
flate2 = "0.2"
fs2 = "0.3"
git2 = "0.6"
git2-curl = "0.7"
glob = "0.2"
kernel32-sys = "0.2"
libc = "0.2"
libgit2-sys = "0.6"
log = "0.3"
miow = "0.1"
num_cpus = "1.0"
psapi-sys = "0.1"
regex = "0.1"
rustc-serialize = "0.3"
semver = "0.5.0"
tempdir = "0.3"
term = "0.4.4"
toml = "0.2"
url = "1.1"
winapi = "0.2"

[dependencies.crates-io]
version = "0.5"

[dependencies.tar]
default-features = false
version = "0.4"

[dev-dependencies]
bufstream = "0.1"
filetime = "0.1"
hamcrest = "0.1"

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[package]
authors = ["Yehuda Katz <wycats@gmail.com>", "Carl Lerche <me@carllerche.com>", "Alex Crichton <alex@alexcrichton.com>"]
description = "Cargo, a package manager for Rust.\n"
documentation = "http://doc.crates.io/cargo"
homepage = "https://crates.io"
license = "MIT/Apache-2.0"
name = "cargo"
repository = "https://github.com/rust-lang/cargo"
version = "0.15.0"

[target]
[target."cfg(unix)"]
[target."cfg(unix)".dependencies]
openssl = "0.9"
