[dependencies]
chrono = "0.2"
clap = "^2.9"
horrorshow = "0.5"
lazy_static = "0.2"
slug = "0.1"

[dependencies.gazetta-core]
version = "0.1"

[package]
authors = ["Steven Allen <steven@stebalien.com>"]
description = "A static site generator framework. Shared CLI code."
documentation = "https://stebalien.github.io/gazetta/gazetta_cli/"
homepage = "http://stebalien.com/projects/gazetta"
keywords = ["staticsite", "website", "blog"]
license = "GPL-3.0"
name = "gazetta-cli"
repository = "https://github.com/Stebalien/gazetta"
version = "0.1.3"
