[[bin]]
name = "webfonts1"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^1.0"

[dependencies.google-webfonts1]
default-features = false
optional = true
version = "1.0.2+20160302"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-webfonts1/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-webfonts1/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with webfonts (protocol v1)"
documentation = "http://byron.github.io/google-apis-rs/google_webfonts1_cli"
homepage = "https://developers.google.com/fonts/docs/developer_api"
keywords = ["webfonts", "google", "cli"]
license = "MIT"
name = "google-webfonts1-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/webfonts1-cli"
version = "1.0.2+20160302"
