[[bin]]
name = "drive2"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^1.0"

[dependencies.google-drive2]
default-features = false
optional = true
version = "1.0.2+20161212"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-drive2/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-drive2/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with drive (protocol v2)"
documentation = "http://byron.github.io/google-apis-rs/google_drive2_cli"
homepage = "https://developers.google.com/drive/"
keywords = ["drive", "google", "cli"]
license = "MIT"
name = "google-drive2-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/drive2-cli"
version = "1.0.2+20161212"
