[[bin]]
name = "reseller1-sandbox"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^1.0"

[dependencies.google-reseller1_sandbox]
default-features = false
optional = true
version = "1.0.2+20160329"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-reseller1_sandbox/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-reseller1_sandbox/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with reseller (protocol v1sandbox)"
documentation = "http://byron.github.io/google-apis-rs/google_reseller1_sandbox_cli"
homepage = "https://developers.google.com/google-apps/reseller/"
keywords = ["reseller", "google", "cli"]
license = "MIT"
name = "google-reseller1_sandbox-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/reseller1_sandbox-cli"
version = "1.0.2+20160329"
