[[bin]]
name = "manager1-beta2"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^1.0"

[dependencies.google-manager1_beta2]
default-features = false
optional = true
version = "1.0.2+20140915"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-manager1_beta2/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-manager1_beta2/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with manager (protocol v1beta2)"
documentation = "http://byron.github.io/google-apis-rs/google_manager1_beta2_cli"
homepage = "https://developers.google.com/deployment-manager/"
keywords = ["manager", "google", "cli"]
license = "MIT"
name = "google-manager1_beta2-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/manager1_beta2-cli"
version = "1.0.2+20140915"
