[[bin]]
name = "youtube3"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^1.0"

[dependencies.google-youtube3]
default-features = false
optional = true
version = "1.0.2+20161202"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-youtube3/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-youtube3/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with YouTube (protocol v3)"
documentation = "http://byron.github.io/google-apis-rs/google_youtube3_cli"
homepage = "https://developers.google.com/youtube/v3"
keywords = ["youtube", "google", "cli"]
license = "MIT"
name = "google-youtube3-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/youtube3-cli"
version = "1.0.2+20161202"
