[[bin]]
name = "gamesconfiguration1-configuration"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^1.0"

[dependencies.google-gamesconfiguration1_configuration]
default-features = false
optional = true
version = "1.0.2+20161207"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-gamesconfiguration1_configuration/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-gamesconfiguration1_configuration/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with Games Configuration (protocol v1configuration)"
documentation = "http://byron.github.io/google-apis-rs/google_gamesconfiguration1_configuration_cli"
homepage = "https://developers.google.com/games/services"
keywords = ["gamesConfiguration", "google", "cli"]
license = "MIT"
name = "google-gamesconfiguration1_configuration-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/gamesconfiguration1_configuration-cli"
version = "1.0.2+20161207"
