[[bin]]
name = "dfareporting2d6"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.9"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^1.0"

[dependencies.google-dfareporting2d6]
default-features = false
optional = true
version = "1.0.2+20161027"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-dfareporting2d6/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-dfareporting2d6/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with dfareporting (protocol v2.6)"
documentation = "http://byron.github.io/google-apis-rs/google_dfareporting2d6_cli"
homepage = "https://developers.google.com/doubleclick-advertisers/"
keywords = ["dfareporting", "google", "cli"]
license = "MIT"
name = "google-dfareporting2d6-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/dfareporting2d6-cli"
version = "1.0.2+20161027"
