[dependencies]
[dependencies.libgpg-error-sys]
version = "0.2.0"

[package]
authors = ["John Schug <john.ips.schug@gmail.com>"]
description = "Libgpg-error bindings for Rust"
documentation = "https://johnschug.github.io/rust-gpg-error"
keywords = ["gpg"]
license = "LGPL-2.1"
name = "gpg-error"
repository = "https://github.com/johnschug/rust-gpg-error"
version = "0.2.0"
