[dependencies]
[dependencies.lyon_core]
version = "0.2.0"

[dependencies.lyon_extra]
version = "0.2.0"

[dependencies.lyon_tessellation]
version = "0.2.0"

[lib]
name = "lyon_svg"
path = "src/lib.rs"

[package]
authors = ["Nicolas Silva <nical@fastmail.com>"]
description = "[TODO] High-level SVG rendering library on top of lyon's tesselator."
license = "MIT/Apache-2.0"
name = "lyon_svg"
repository = "https://github.com/nical/lyon"
version = "0.2.0"
