[dependencies]
[dependencies.phf_shared]
version = "=0.4.9"

[dependencies.time]
optional = true
version = "0.1"

[features]
stats = ["time"]

[lib]
name = "phf_mac"
path = "src/lib.rs"
plugin = true
test = false

[package]
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Compiler plugin for perfect hash function data structures"
license = "MIT"
name = "phf_mac"
repository = "https://github.com/sfackler/rust-phf"
version = "0.4.9"
