[[bench]]
name = "bench"

[dependencies]
byteorder = "1"
lazy_static = "0.2"

[dependencies.snappy-cpp]
optional = true
version = "0.1"

[dev-dependencies]
quickcheck = "0.4"
rand = "0.3"

[features]
cpp = ["snappy-cpp"]

[lib]
bench = false

[package]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A pure Rust implementation of the Snappy compression algorithm. Includes\nstreaming compression and decompression.\n"
documentation = "https://docs.rs/snap"
homepage = "https://github.com/BurntSushi/rust-snappy"
keywords = ["snappy", "compress", "compression", "decompress", "decompression"]
license = "BSD-3-Clause"
name = "snap"
readme = "README.md"
repository = "https://github.com/BurntSushi/rust-snappy"
version = "0.2.1"

[profile]
[profile.release]
debug = true

[profile.test]
opt-level = 3
