[dependencies]
[dependencies.syntex_errors]
version = "0.58"

[dependencies.syntex_syntax]
version = "0.58"

[package]
authors = ["erick.tryzelaar@gmail.com"]
description = "A library that enables compile time syntax extension expansion"
include = ["Cargo.toml", "src/**/*.rs"]
license = "MIT/Apache-2.0"
name = "syntex"
readme = "../README.md"
repository = "https://github.com/erickt/rust-syntex"
version = "0.58.0"
