[[bin]]
name = "doubleclicksearch2"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.9"
serde_derive = "^ 0.9"
serde_json = "^ 0.9"
strsim = "^0.5"
yup-hyper-mock = "^2.0"
yup-oauth2 = "^ 1.0"

[dependencies.google-doubleclicksearch2]
version = "1.0.4+20161108"

[features]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with doubleclicksearch (protocol v2)"
documentation = "http://byron.github.io/google-apis-rs/google_doubleclicksearch2_cli"
homepage = "https://developers.google.com/doubleclick-search/"
keywords = ["doubleclicksearch", "google", "cli"]
license = "MIT"
name = "google-doubleclicksearch2-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/doubleclicksearch2-cli"
version = "1.0.4+20161108"
