[dependencies]
alga = "0.5"
approx = "0.1"
nalgebra = "0.11"
num-traits = "0.1"
rustc-serialize = "0.3"

[dependencies.ncollide_geometry]
version = "0.3"

[dependencies.ncollide_math]
version = "0.6"

[dependencies.ncollide_procedural]
version = "0.6"

[dependencies.ncollide_utils]
version = "0.6"

[lib]
name = "ncollide_transformation"
path = "lib.rs"

[package]
authors = ["SÃ©bastien Crozet <developer@crozet.re>"]
description = "2 and 3-dimensional collision detection library in Rust: module for transforming a geometric entity to another one by means of approximation/fitting."
documentation = "http://ncollide.org/rustdoc/ncollide_transformation"
homepage = "http://ncollide.org"
keywords = ["collision", "geometry", "distance", "ray", "convex"]
license = "BSD-3-Clause"
name = "ncollide_transformation"
repository = "https://github.com/sebcrozet/ncollide"
version = "0.6.0"
