[dependencies]
rayon = "0.6"

[dependencies.ndarray]
version = "0.8.0"

[dev-dependencies]
num_cpus = "1.2"

[package]
authors = ["bluss"]
categories = ["data-structures", "science", "concurrency"]
description = "Parallelization for ndarray (using rayon)."
documentation = "https://docs.rs/ndarray-parallel/"
keywords = ["data-structure", "multidimensional", "parallel", "concurrent"]
license = "MIT/Apache-2.0"
name = "ndarray-parallel"
repository = "https://github.com/bluss/rust-ndarray"
version = "0.2.0"
