[build-dependencies]
[build-dependencies.winapi-build]
version = "0.1.1"

[dependencies]
[dependencies.winapi]
version = "0.2.5"

[lib]
name = "netapi32"

[package]
authors = ["Peter Atashian <retep998@gmail.com>"]
build = "build.rs"
description = "Contains function definitions for the Windows API library netapi32. See winapi for types and constants."
documentation = "https://retep998.github.io/doc/netapi32/"
keywords = ["windows", "ffi", "win32"]
license = "MIT"
name = "netapi32-sys"
readme = "README.md"
repository = "https://github.com/retep998/winapi-rs"
version = "0.2.0"
