[dependencies]
[dependencies.num-integer]
optional = false
version = "0.1.32"

[dependencies.num-traits]
optional = false
version = "0.1.32"

[package]
authors = ["The Rust Project Developers"]
description = "External iterators for generic mathematics"
documentation = "http://rust-num.github.io/num"
homepage = "https://github.com/rust-num/num"
keywords = ["mathematics", "numerics"]
license = "MIT/Apache-2.0"
name = "num-iter"
repository = "https://github.com/rust-num/num"
version = "0.1.33"
