[build-dependencies]
[build-dependencies.pnet_macros]
version = ">=0.6"

[build-dependencies.syntex]
optional = true
version = "0.42.*"

[dependencies]
[dependencies.clippy]
optional = true
version = ">=0.0"

[dependencies.libc]
version = "0.2.*"

[dependencies.netmap_sys]
features = ["netmap_with_libs"]
optional = true
version = ">=0.0"

[dependencies.pnet_macros]
default-features = false
features = []
optional = true
version = ">=0.9"

[dependencies.pnet_macros_plugin]
optional = true
version = ">=0.1"

[dependencies.pnet_macros_support]
version = ">=0.1"

[dependencies.syntex]
optional = true
version = "0.42.*"

[dependencies.winapi]
version = "0.2.*"

[dependencies.ws2_32-sys]
version = "0.2.*"

[dev-dependencies]
time = ">=0.1"

[features]
appveyor = []
benchmark = []
default = ["with-syntex"]
netmap = ["netmap_sys"]
nightly = ["pnet_macros_plugin"]
travis = []
with-syntex = ["syntex", "pnet_macros/with-syntex"]

[lib]
name = "pnet"

[package]
authors = ["Robert Clipsham <robert@octarineparrot.com>"]
build = "build.rs"
description = "Cross-platform, low level networking using the Rust programming language."
documentation = "http://octarineparrot.com/assets/libpnet/doc/pnet/"
homepage = "https://github.com/libpnet/libpnet"
keywords = ["networking", "transport", "datalink", "packet", "protocol"]
license = "MIT/Apache-2.0"
name = "pnet"
readme = "README.md"
repository = "https://github.com/libpnet/libpnet"
version = "0.14.0"
