[dependencies]
libc = "0.2.13"
rustc-serialize = "0.3.16"
term = "0.4.4"
unicode-xid = "0.0.4"

[dependencies.syntex_pos]
version = "0.58"

[package]
authors = ["erick.tryzelaar@gmail.com"]
description = "Export of librustc_errors for code generation"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
name = "syntex_errors"
readme = "../README.md"
repository = "https://github.com/serde-rs/syntex"
version = "0.58.1"
