[dependencies]
derive-new = "0.4"
rand = "0.3.14"

[dev-dependencies]
quickcheck = "0.4.1"

[features]
unstable = []

[lib]
name = "teardown_tree"
path = "src/lib.rs"

[package]
authors = ["Kirill Khazan <kirillkh@gmail.com>"]
description = "A binary search tree that supports fast clone and delete-range operations"
homepage = "https://github.com/kirillkh/rs_teardown_tree"
keywords = ["BST", "tree", "teardown"]
license-file = "LICENSE-MIT"
name = "teardown_tree"
readme = "README.rst"
repository = "https://github.com/kirillkh/rs_teardown_tree.git"
version = "0.6.6"

[profile]
[profile.dev]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0

[profile.release]
codegen-units = 1
debug = true
debug-assertions = false
lto = true
opt-level = 3
rpath = false
