[badges]
[badges.travis-ci]
repository = "vberger/wayland-client-rs"

[build-dependencies]
[build-dependencies.wayland-scanner]
version = "0.7.8"

[dependencies]
bitflags = "0.7"
libc = "0.2"

[dependencies.wayland-sys]
features = ["client"]
version = "0.7.8"

[dev-dependencies]
byteorder = "0.5"
tempfile = "2"

[features]
cursor = ["wayland-sys/cursor"]
default = ["egl", "cursor"]
dlopen = ["wayland-sys/dlopen"]
egl = ["wayland-sys/egl"]

[package]
authors = ["Victor Berger <victor.berger@m4x.org>"]
build = "build.rs"
categories = ["gui", "api-bindings"]
description = "Bindings to the standard C implementation of the wayland protocol, client side."
documentation = "https://vberger.github.io/wayland-client-rs/wayland_client/"
keywords = ["wayland", "client"]
license = "MIT"
name = "wayland-client"
repository = "https://github.com/vberger/wayland-client-rs"
version = "0.7.8"
