[dependencies]
libc = "0.1"

[dependencies.allegro]
version = "=0.0.29"

[dependencies.allegro_color-sys]
version = "=0.0.29"

[dependencies.allegro_util]
version = "=0.0.29"

[features]
link_debug = ["allegro_color-sys/link_debug"]
link_none = ["allegro_color-sys/link_none"]
link_static = ["allegro_color-sys/link_static"]

[lib]
name = "allegro_color"
path = "src/lib.rs"

[package]
authors = ["SiegeLord <slabode@aim.com>"]
description = "Allegro 5 color addon Rust wrapper"
documentation = "http://siegelord.github.io/RustAllegro/doc/allegro_color/index.html"
keywords = ["colors"]
license = "Zlib"
name = "allegro_color"
repository = "https://github.com/SiegeLord/RustAllegro"
version = "0.0.29"
