[dependencies]
libc = "0.1"

[dependencies.allegro-sys]
version = "=0.0.29"

[dependencies.allegro_util]
version = "=0.0.29"

[features]
link_debug = ["allegro-sys/link_debug"]
link_none = ["allegro-sys/link_none"]
link_static = ["allegro-sys/link_static"]

[lib]
name = "allegro"
path = "src/lib.rs"

[package]
authors = ["SiegeLord <slabode@aim.com>"]
build = "build.rs"
description = "Allegro 5 core library Rust wrapper"
documentation = "http://siegelord.github.io/RustAllegro/doc/allegro/index.html"
keywords = ["input", "windowing", "opengl", "direct3d", "graphics"]
license = "Zlib"
name = "allegro"
repository = "https://github.com/SiegeLord/RustAllegro"
version = "0.0.29"

[[test]]
harness = false
name = "init_test"
path = "src/init_test.rs"
