[dependencies]
libc = "0.1"

[dependencies.allegro]
version = "=0.0.29"

[dependencies.allegro_audio-sys]
version = "=0.0.29"

[dependencies.allegro_util]
version = "=0.0.29"

[features]
link_debug = ["allegro_audio-sys/link_debug"]
link_none = ["allegro_audio-sys/link_none"]
link_static = ["allegro_audio-sys/link_static"]

[lib]
name = "allegro_audio"
path = "src/lib.rs"

[package]
authors = ["SiegeLord <slabode@aim.com>"]
description = "Allegro 5 audio addon Rust wrapper"
documentation = "http://siegelord.github.io/RustAllegro/doc/allegro_audio/index.html"
keywords = ["audio"]
license = "Zlib"
name = "allegro_audio"
repository = "https://github.com/SiegeLord/RustAllegro"
version = "0.0.29"
