[badges]
[badges.appveyor]
repository = "alexcrichton/curl-rust"

[badges.travis-ci]
repository = "alexcrichton/curl-rust"

[dependencies]
libc = "0.2"

[dependencies.curl-sys]
version = "0.3.7"

[dev-dependencies]
mio = "0.6"

[package]
authors = ["Carl Lerche <me@carllerche.com>", "Alex Crichton <alex@alexcrichton.com>"]
categories = ["api-bindings", "web-programming::http-client"]
description = "Rust bindings to libcurl for making HTTP requests"
documentation = "https://docs.rs/curl"
homepage = "https://github.com/alexcrichton/curl-rust"
license = "MIT"
name = "curl"
repository = "https://github.com/alexcrichton/curl-rust"
version = "0.4.4"

[target]
[target."cfg(all(unix, not(target_os = \"macos\")))"]
[target."cfg(all(unix, not(target_os = \"macos\")))".dependencies]
openssl-probe = "0.1"
openssl-sys = "0.9.0"

[target."cfg(windows)"]
[target."cfg(windows)".dependencies]
winapi = "0.2"
