[dependencies]
[dependencies.docopt]
version = "0.6.80"

[dev-dependencies]
rustc-serialize = "0.3"

[lib]
name = "docopt_macros"
path = "src/macro.rs"
plugin = true

[package]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Docopt macro for command line argument parsing."
documentation = "http://burntsushi.net/rustdoc/docopt/"
homepage = "https://github.com/docopt/docopt.rs"
keywords = ["docopt", "argument", "command", "argv"]
license = "Unlicense/MIT"
name = "docopt_macros"
readme = "../README.md"
repository = "https://github.com/docopt/docopt.rs"
version = "0.6.88"
