[dependencies]
bitflags = "0.7"
cfg-if = "0.1"
gpg-error = "0.2"
lazy_static = "0.2"
libc = "0.2"

[dependencies.libgcrypt-sys]
default-features = false
features = ["shim"]
version = "0.5.0"

[features]
default = ["v1_7_0"]
nightly = []
v1_6_0 = ["libgcrypt-sys/v1_6_0"]
v1_7_0 = ["v1_6_0", "libgcrypt-sys/v1_7_0"]

[package]
authors = ["John Schug <john.ips.schug@gmail.com>"]
description = "Libgcrypt bindings for Rust"
documentation = "https://johnschug.github.io/rust-gcrypt"
keywords = ["crypto", "cryptography"]
license = "LGPL-2.1"
name = "gcrypt"
repository = "https://github.com/johnschug/rust-gcrypt"
version = "0.5.0"
