[[bin]]
name = "appengine1-beta5"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^2.0"

[dependencies.google-appengine1_beta5]
default-features = false
optional = true
version = "1.0.3+20161208"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-appengine1_beta5/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-appengine1_beta5/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with appengine (protocol v1beta5)"
documentation = "http://byron.github.io/google-apis-rs/google_appengine1_beta5_cli"
homepage = "https://cloud.google.com/appengine/docs/admin-api/"
keywords = ["appengine", "google", "cli"]
license = "MIT"
name = "google-appengine1_beta5-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/appengine1_beta5-cli"
version = "1.0.3+20161208"
