[[bin]]
name = "fusiontables2"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^2.0"

[dependencies.google-fusiontables2]
default-features = false
optional = true
version = "1.0.3+20160526"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-fusiontables2/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-fusiontables2/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with fusiontables (protocol v2)"
documentation = "http://byron.github.io/google-apis-rs/google_fusiontables2_cli"
homepage = "https://developers.google.com/fusiontables"
keywords = ["fusiontables", "google", "cli"]
license = "MIT"
name = "google-fusiontables2-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/fusiontables2-cli"
version = "1.0.3+20160526"
