[[bin]]
name = "replicapoolupdater1-beta1"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^2.0"

[dependencies.google-replicapoolupdater1_beta1]
default-features = false
optional = true
version = "1.0.3+20161003"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-replicapoolupdater1_beta1/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-replicapoolupdater1_beta1/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with replicapoolupdater (protocol v1beta1)"
documentation = "http://byron.github.io/google-apis-rs/google_replicapoolupdater1_beta1_cli"
homepage = "https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service"
keywords = ["replicapoolupdater", "google", "cli"]
license = "MIT"
name = "google-replicapoolupdater1_beta1-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/replicapoolupdater1_beta1-cli"
version = "1.0.3+20161003"
