[[bin]]
name = "logging2-beta1"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^2.0"

[dependencies.google-logging2_beta1]
default-features = false
optional = true
version = "1.0.3+20161206"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-logging2_beta1/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-logging2_beta1/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with Logging (protocol v2beta1)"
documentation = "http://byron.github.io/google-apis-rs/google_logging2_beta1_cli"
homepage = "https://cloud.google.com/logging/docs/"
keywords = ["logging", "google", "cli"]
license = "MIT"
name = "google-logging2_beta1-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/logging2_beta1-cli"
version = "1.0.3+20161206"
