[[bin]]
name = "manufacturers1"

[build-dependencies]
[build-dependencies.serde_codegen]
optional = true
version = "^ 0.8"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.8"
serde_json = "^ 0.8"
strsim = "^0.5"
yup-hyper-mock = "^2.0"

[dependencies.google-manufacturers1]
default-features = false
optional = true
version = "1.0.3+20161028"

[dependencies.serde_derive]
optional = true
version = "^ 0.8"

[dependencies.yup-oauth2]
default-features = false
optional = true
version = "^ 1.0"

[features]
default = ["with-serde-codegen"]
nightly = ["serde_derive", "yup-oauth2/nightly", "google-manufacturers1/nightly"]
with-serde-codegen = ["serde_codegen", "yup-oauth2/with-serde-codegen", "google-manufacturers1/with-serde-codegen"]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with Manufacturer Center (protocol v1)"
documentation = "http://byron.github.io/google-apis-rs/google_manufacturers1_cli"
homepage = "https://developers.google.com/manufacturers/"
keywords = ["manufacturers", "google", "cli"]
license = "MIT"
name = "google-manufacturers1-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/manufacturers1-cli"
version = "1.0.3+20161028"
