[features]
default = ["std"]
max_level_debug = []
max_level_error = []
max_level_info = []
max_level_off = []
max_level_trace = []
max_level_warn = []
release_max_level_debug = []
release_max_level_error = []
release_max_level_info = []
release_max_level_off = []
release_max_level_trace = []
release_max_level_warn = []
std = []

[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Structured, composable logging for Rust"
documentation = "https://docs.rs/slog"
homepage = "https://github.com/slog-rs/slog"
keywords = ["log", "logging", "structured", "hierarchical"]
license = "MPL-2.0"
name = "slog"
readme = "README.md"
repository = "https://github.com/slog-rs/slog"
version = "1.4.1"

[profile]
[profile.bench]
debug = false
debug-assertions = false
lto = true
opt-level = 3

[profile.release]
debug = false
debug-assertions = false
lto = true
opt-level = 3
