[dependencies]
bitflags = "^0.7.0"
libc = "^0.2.13"
log = "^0.3.6"
rustc-serialize = "^0.3.16"
term = "^0.4.4"
unicode-xid = "^0.0.3"

[dependencies.syntex_errors]
version = "^0.52.0"

[dependencies.syntex_pos]
version = "^0.52.0"

[package]
authors = ["erick.tryzelaar@gmail.com"]
description = "Export of libsyntax for code generation"
include = ["Cargo.toml", "src/**/*.rs"]
license = "MIT/Apache-2.0"
name = "syntex_syntax"
repository = "https://github.com/serde-rs/syntex"
version = "0.52.0"
