[badges]
[badges.travis-ci]
repository = "Drakulix/wlc"

[dependencies]
bitflags = "0.7"
lazy_static = "0.2"
libc = "0.2"
log = "0.3"
num-traits = "^0.1.35"
uinput-sys = "0.1"
xkbcommon = "0.2"

[dependencies.serde]
optional = true
version = "0.9"

[dependencies.serde_derive]
optional = true
version = "0.9"

[dependencies.wayland-server]
optional = true
version = "0.7"

[dependencies.wlc-sys]
version = "0.0.7"

[features]
default = []
render = []
serialization = ["serde", "serde_derive"]
static = ["wlc-sys/static"]
unsafe-stable = []
wayland = ["wayland-server"]

[package]
authors = ["Victor Brekenfeld (Drakulix) <github@drakulix.de>"]
categories = ["external-ffi-bindings", "gui"]
description = "Safe Bindings for Cloudef's wlc (Wayland Compositor C-Library)"
documentation = "https://drakulix.github.io/wlc"
exclude = [".travis.yml", ".rustfmt.toml"]
keywords = ["wayland", "compositor", "bindings"]
license = "MIT"
name = "wlc"
readme = "README.md"
repository = "https://github.com/Drakulix/wlc"
version = "0.1.0"
