[dependencies]
[dependencies.clippy]
optional = true
version = "0.0"

[dependencies.commoncrypto-sys]
version = "0.2.0"

[dev-dependencies]
hex = "0.2"

[features]
lint = ["clippy"]

[package]
authors = ["Mark Lee"]
description = "Idiomatic Rust wrappers for Mac OS X's CommonCrypto library"
documentation = "https://docs.rs/commoncrypto"
keywords = ["crypto", "hash", "digest", "osx", "commoncrypto"]
license = "MIT"
name = "commoncrypto"
repository = "https://github.com/malept/rust-commoncrypto"
version = "0.2.0"
