[dependencies]
lazy_static = "0.2"

[dependencies.gazetta-core]
version = "0.1"

[package]
authors = ["Steven Allen <steven@stebalien.com>"]
description = "A static site generator framework. Extra models."
documentation = "https://stebalien.github.io/gazetta/gazetta_model_ext/"
homepage = "http://stebalien.com/projects/gazetta"
keywords = ["staticsite", "website", "blog"]
license = "GPL-3.0"
name = "gazetta-model-ext"
repository = "https://github.com/Stebalien/gazetta"
version = "0.1.1"
