[dependencies]
gfx_gl = "0.3.1"
log = "0.3"

[dependencies.gfx_core]
version = "0.6"

[lib]
name = "gfx_device_gl"

[package]
authors = ["The Gfx-rs Developers"]
description = "OpenGL backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
name = "gfx_device_gl"
repository = "https://github.com/gfx-rs/gfx"
version = "0.13.0"
