[dependencies]
atty = "0.1.2"
bit-set = "0.3.0"
bitflags = "0.4.0"
diff = "0.1"
docopt = "0.6"
itertools = "0.3"
petgraph = "0.1.11"
regex = "0.1"
regex-syntax = "0.2"
rustc-serialize = "0.3"
term = "0.4.4"
unicode-xid = "0.0.2"

[dependencies.lalrpop-intern]
version = "0.12.5"

[dependencies.lalrpop-util]
version = "0.12.5"

[dev-dependencies]
rand = "0.3"

[package]
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
description = "snapshot of LALRPOP for use in bootstrapping"
license = "Apache-2.0/MIT"
name = "lalrpop-snap"
repository = "https://github.com/nikomatsakis/lalrpop"
version = "0.12.5"
workspace = ".."
