[dependencies]
bufstream = "0.1"
fallible-iterator = "0.1.3"
hex = "0.2"
log = "0.3"
postgres-protocol = "0.2"

[dependencies.native-tls]
optional = true
version = "0.1"

[dependencies.openssl]
optional = true
version = "0.9.2"

[dependencies.postgres-shared]
version = "0.2"

[dependencies.rustc-serialize]
optional = true
version = "0.3"

[dependencies.schannel]
optional = true
version = "0.1"

[dependencies.security-framework]
optional = true
version = "0.1.2"

[dev-dependencies]
bit-vec = "0.4"
chrono = "0.3"
eui48 = "0.1"
rustc-serialize = "0.3"
serde_json = "0.9"
time = "0.1.14"
url = "1.0"
uuid = "0.4"

[features]
no-logging = []
with-bit-vec = ["postgres-shared/with-bit-vec"]
with-chrono = ["postgres-shared/with-chrono"]
with-eui48 = ["postgres-shared/with-eui48"]
with-native-tls = ["native-tls"]
with-openssl = ["openssl"]
with-rustc-serialize = ["postgres-shared/with-rustc-serialize"]
with-schannel = ["schannel"]
with-security-framework = ["security-framework"]
with-serde_json = ["postgres-shared/with-serde_json"]
with-time = ["postgres-shared/with-time"]
with-uuid = ["postgres-shared/with-uuid"]

[lib]
bench = false
name = "postgres"
path = "src/lib.rs"
test = false

[package]
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "A native PostgreSQL driver"
documentation = "https://docs.rs/postgres/0.14.0/postgres"
include = ["src/*", "Cargo.toml", "LICENSE", "README.md", "THIRD_PARTY"]
keywords = ["database", "postgres", "postgresql", "sql"]
license = "MIT"
name = "postgres"
readme = "../README.md"
repository = "https://github.com/sfackler/rust-postgres"
version = "0.14.0"

[[test]]
name = "test"
path = "tests/test.rs"
