[dependencies]
libc = "0.2"

[dependencies.num-complex]
default-features = false
version = "0.1.35"

[dependencies.tensorflow-sys]
version = "0.7.0"

[dev-dependencies]
random = "0.12"

[features]
tensorflow_unstable = []

[package]
authors = ["Adam Crume <acrume@google.com>"]
description = "Rust language bindings for TensorFlow."
documentation = "https://tensorflow.github.io/rust/tensorflow"
keywords = ["TensorFlow", "bindings"]
license = "Apache-2.0"
name = "tensorflow"
readme = "README.md"
repository = "https://github.com/tensorflow/rust"
version = "0.3.1"
