[dependencies]
futures = "0.1.2"
quick-error = "1.1.0"
rand = "0.3.14"

[dev-dependencies]
argparse = "0.2.1"
domain = "0.1.0"
futures-cpupool = "0.1.2"
ns-std-threaded = "0.1.0"
tokio-core = "0.1.0"

[lib]
name = "abstract_ns"

[package]
authors = ["paul@colomiets.name"]
description = "    Abstract name service traits for use with futures (and tokio)\n"
documentation = "http://tailhook.github.io/abstract-ns"
homepage = "http://github.com/tailhook/abstract-ns"
keywords = ["dns", "tokio", "name", "service", "discovery"]
license = "MIT/Apache-2.0"
name = "abstract-ns"
readme = "README.rst"
version = "0.3.1"

[replace]
[replace."abstract-ns:0.3.1"]
path = "."
