[dependencies]
[dependencies.bindgen]
version = "*"

[features]
static = []

[lib]
name = "bindgen_plugin"
path = "src/lib.rs"
plugin = true

[package]
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
description = "A binding generator for Rust - compiler plugin"
license = "BSD-3-Clause"
name = "bindgen_plugin"
version = "0.15.0"
