[dependencies]
libc = "0.2.11"

[dependencies.clippy]
optional = true
version = "0.0.108"

[dependencies.fitsio-sys]
version = "0.2.3"

[dev-dependencies]
tempdir = "0.3.4"

[features]
default = []

[package]
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]
categories = ["external-ffi-bindings", "science"]
description = "Rust implmentation of astronomy fits file handling"
documentation = "https://docs.rs/fitsio"
homepage = "https://github.com/mindriot101/rust-fitsio"
license = "MIT/Apache-2.0"
name = "fitsio"
readme = "README.md"
repository = "https://github.com/mindriot101/rust-fitsio"
version = "0.5.2"
