[dependencies]
draw_state = "0.6"
log = "0.3"

[dependencies.gfx_core]
version = "0.6"

[features]
unstable = []

[lib]
name = "gfx"
path = "src/lib.rs"

[package]
authors = ["The Gfx-rs Developers"]
description = "A high-performance, bindless graphics API"
homepage = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
name = "gfx"
repository = "https://github.com/gfx-rs/gfx"
version = "0.14.0"
