[[bin]]
name = "adexchangebuyer1d3"

[dependencies]
clap = "^2.0"
hyper = "^ 0.10"
hyper-rustls = "^0.3"
mime = "^ 0.2.0"
serde = "^ 0.9"
serde_derive = "^ 0.9"
serde_json = "^ 0.9"
strsim = "^0.5"
yup-hyper-mock = "^2.0"
yup-oauth2 = "^ 1.0"

[dependencies.google-adexchangebuyer1d3]
version = "1.0.4+20161020"

[features]

[package]
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "A complete library to interact with Ad Exchange Buyer (protocol v1.3)"
documentation = "http://byron.github.io/google-apis-rs/google_adexchangebuyer1d3_cli"
homepage = "https://developers.google.com/ad-exchange/buyer-rest"
keywords = ["adexchangebuyer", "google", "cli"]
license = "MIT"
name = "google-adexchangebuyer1d3-cli"
repository = "https://github.com/Byron/google-apis-rs/tree/master/gen/adexchangebuyer1d3-cli"
version = "1.0.4+20161020"
