[dependencies]
[dependencies.libdw-sys]
optional = false
version = "0.0.1"

[package]
authors = ["Josh Stone <jistone@redhat.com>"]
description = "Placeholder for bindings to elfutils"
license = "MIT/Apache-2.0"
name = "libdwfl"
repository = "https://github.com/cuviper/elfutils-rs"
version = "0.0.1"
