[dependencies]
[dependencies.pistoncore-event_loop]
version = "0.26.0"

[dependencies.pistoncore-input]
version = "0.14.0"

[dependencies.pistoncore-window]
version = "0.23.0"

[lib]
name = "piston"
path = "./src/lib.rs"

[package]
authors = ["bvssvni <bvssvni@gmail.com>", "Coeuvre <coeuvre@gmail.com>", "gmorenz", "leonkunert <info@leonkunert.de>", "mitchmindtree <me@michellnordine.com>", "Christiandh", "Apointos", "ccgn", "reem", "TyOverby <ty@pre-alpha.com>", "eddyb", "Phlosioneer <mattmdrr2@gmail.com"]
description = "The Piston game engine core libraries"
documentation = "http://www.piston.rs/docs/piston/piston/index.html"
homepage = "https://github.com/PistonDevelopers/piston"
keywords = ["piston", "game", "engine", "core"]
license = "MIT"
name = "piston"
repository = "https://github.com/PistonDevelopers/piston.git"
version = "0.26.0"
