[dependencies]
bitflags = "0.7"
libc = "0.2"

[dependencies.libssh2-sys]
version = "0.2.4"

[dev-dependencies]
tempdir = "0.3"

[package]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
description = "Bindings to libssh2 for interacting with SSH servers and executing remote\ncommands, forwarding local ports, etc.\n"
documentation = "http://alexcrichton.com/ssh2-rs"
homepage = "https://github.com/alexcrichton/ssh2-rs"
keywords = ["ssh"]
license = "MIT/Apache-2.0"
name = "ssh2"
readme = "README.md"
repository = "https://github.com/alexcrichton/ssh2-rs"
version = "0.3.1"

[[test]]
name = "all"
