[badges]
[badges.travis-ci]
repository = "vberger/wayland-client-rs"

[build-dependencies]
[build-dependencies.wayland-scanner]
version = "0.8.4"

[dependencies]
bitflags = "0.7"

[dependencies.wayland-client]
optional = true
version = "0.8.4"

[dependencies.wayland-server]
optional = true
version = "0.8.4"

[dependencies.wayland-sys]
version = "0.8.4"

[features]
client = ["wayland-client"]
nightly = []
server = ["wayland-server"]
unstable_protocols = []

[package]
authors = ["Victor Berger <victor.berger@m4x.org>"]
build = "build.rs"
categories = ["gui", "api-bindings"]
description = "Generated API for the officials wayland protocol extensions"
documentation = "https://vberger.github.io/wayland-client-rs/wayland_protocols/"
keywords = ["wayland", "client", "server", "protocol", "extension"]
license = "MIT"
name = "wayland-protocols"
repository = "https://github.com/vberger/wayland-client-rs"
version = "0.8.4"
